### ISSUE TITLE
코스트맵 서브모듈 미추가 이슈

### ISSUE THREAD

**Issue by ggh-png** [AuTURBO/RDSim#22]
![image](https://github.com/user-attachments/assets/4cf8fb32-b420-43ce-ba8b-8c6c7858876a)

로컬 코스트맵 서브 모듈 추가를 안하셔서 작동이 안되는것 같은데 확인한번 부탁 드릴 수 있을까요?

**Comment by Geonhee-LEE** [comment]
이번에 추가한 의존성 패키지 설치하셨을까요? readme에는 추가해놨습니다. 

$sudo apt install ros-humble-spatio-temporal-voxel-layer -y

**Comment by ggh-png** [comment]
데비안 패키지로 하신걸 모르고 있었네요 죄송합니다 ㅎㅎ 
추가적으로 실행을 해 보았는데 다음과 같이  코스트맵의 잔상이 남아 nav to pose가 정상 작동을 하지 않는 현상이 발생하는데 비슷한 경험이 있으신가요?
![image](https://github.com/user-attachments/assets/dea85a5a-60ea-4412-9cc9-7af2af659954)

**Comment by Geonhee-LEE** [comment]
네, 저도 드리프트 현상이 발생했습니다.
제어 문제인지 위치 추정 문제인지 파악이 되어야 할 것 같습니다. 
https://www.notion.so/ggh-png/2024-10-02-1-11377f2db5c6806993d7fcab410e74fa?pvs=4#0b89fca0c1ef491db23a2e14a9cc5ab9

**Comment by ggh-png** [comment]
지금까지 분석내용 
TF : 문제 없었습니다. 
controller : 말씀하신대로 급발진의 문제만 있을 뿐 코스트맵엔 영향을 끼치지 않는것 같습니다.
costmap : yaml 파일의 voxel_decay 값을 0.3 과 같이 낮추면 빠르게 없어 지지만 근본적인 해결법은 아닌것 같습니다. 
결론 : 건희님이 하시기 전에 기본 voxel layer로 하였을 경우에도 같은 현상이 발생 하였는데 어쩌면 localization 쪽의 문제일 수도 있다는 생각이 드네요 ㅎㅎ  
추가) amcl로 변경하여 진행하면 정상적으로 잘 작동 하네요 ㅎㅎ amcl의 io 부분을 봐바야 겠네요
