### ISSUE TITLE
[ERROR 1729347219.617869862] [bt_navigator]: Original error: Could not load library: libnav2_compute_goal_to_topology_bt_node.so: cannot open shared object file: No such file or directory (./src/lifecycle_node_interface_impl.hpp:503)

### ISSUE THREAD

**Issue by Geonhee-LEE** [AuTURBO/RDSim#36]
`devel/2wheel_diff` 브랜치에서 소스를 가져왔는데, 토폴로지 관련 bt에서 에러가 발생합니다. 혹시 어떤 것이 문제인지 확인 부탁드립니다...!

[ERROR 1729347219.617869862] [bt_navigator]: Original error: Could not load library: libnav2_compute_goal_to_topology_bt_node.so: cannot open shared object file: No such file or directory (./src/lifecycle_node_interface_impl.hpp:503)

![image](https://github.com/user-attachments/assets/b07bdf7b-d0fa-4a65-9d4b-d21c7a47fc32)

**Comment by dawan0111** [comment]
```
ros2 launch rdsim_gazebo rdsim_gps_navigation.launch.py 
```
![image](https://github.com/user-attachments/assets/5d836ad4-8b02-4183-b443-a7f695f4bf40)

위 명령어로 실행시켰을때 제 환경에서는 문제가 없네요.. 혹시 navigation2 submodule update를 하셔도 똑같나요?
```
git submodule update --remote
```

**Comment by Geonhee-LEE** [comment]
NAV2안에 구현이 되어있었군요! 말씀하신대로 서브모듈 업데이트해서 해결해했습니다. 감사합니다


![image](https://github.com/user-attachments/assets/d7ddfa3f-1046-44c6-9490-b4681a185733)
